import type { FilmEntry, FilmCategory } from "@/types"

export const filmCategories: FilmCategory[] = [
  "Offense",
  "Defense",
  "Transition",
  "Rides & Clears",
  "Man-Up/Man-Down",
  "Goalie",
  "Drills",
  "Game Film",
]

/** Color mapping for category badges */
export const filmCategoryColors: Record<FilmCategory, string> = {
  Offense: "text-[var(--btb-red)] border-[var(--btb-red)]/20 bg-[var(--btb-red)]/5",
  Defense: "text-blue-400 border-blue-400/20 bg-blue-400/5",
  Transition: "text-emerald-400 border-emerald-400/20 bg-emerald-400/5",
  "Rides & Clears": "text-emerald-400 border-emerald-400/20 bg-emerald-400/5",
  "Man-Up/Man-Down": "text-amber-400 border-amber-400/20 bg-amber-400/5",
  Goalie: "text-purple-400 border-purple-400/20 bg-purple-400/5",
  Drills: "text-orange-400 border-orange-400/20 bg-orange-400/5",
  "Game Film": "text-white/60 border-white/20 bg-white/5",
}

/** Background color for the video placeholder area */
export const filmCategoryBg: Record<FilmCategory, string> = {
  Offense: "bg-[var(--btb-red)]/15",
  Defense: "bg-blue-500/15",
  Transition: "bg-emerald-500/15",
  "Rides & Clears": "bg-emerald-500/15",
  "Man-Up/Man-Down": "bg-amber-500/15",
  Goalie: "bg-purple-500/15",
  Drills: "bg-orange-500/15",
  "Game Film": "bg-white/10",
}

export const filmLevelColors: Record<string, string> = {
  Beginner: "text-emerald-400/60 border-emerald-400/20 bg-emerald-400/5",
  Intermediate: "text-amber-400/60 border-amber-400/20 bg-amber-400/5",
  Advanced: "text-[var(--btb-red)] border-[var(--btb-red)]/20 bg-[var(--btb-red)]/5",
}

export const films: FilmEntry[] = [
  // ── Offense ──
  {
    id: "off-1",
    title: "Split Dodge & Finish",
    description: "Breakdown of the split dodge technique from X and GLE, with finishing options to both pipe and far side. Covers change of speed, hand positioning, and shot selection.",
    category: "Offense",
    subcategory: "Dodge & Finish",
    videoUrl: "https://www.youtube.com/watch?v=vQfmOqWZa_o",
    duration: "4:30",
    level: "Beginner",
    tags: ["split dodge", "shooting", "attack", "1v1"],
  },
  {
    id: "off-2",
    title: "Roll Dodge Mechanics",
    description: "Proper roll dodge footwork, stick protection, and when to use the roll vs. the split. Film clips from game situations showing high-percentage roll dodge opportunities.",
    category: "Offense",
    subcategory: "Dodge & Finish",
    videoUrl: "https://www.youtube.com/watch?v=RA66O8Mn9X8",
    duration: "5:15",
    level: "Intermediate",
    tags: ["roll dodge", "footwork", "attack", "1v1"],
  },
  {
    id: "off-3",
    title: "2-Man Game: Pick & Roll",
    description: "Pick-and-roll execution from up top and the wing. Covers screen angle, timing of the roll, reading the defender, and finishing options for both the ball carrier and the roller.",
    category: "Offense",
    subcategory: "2-Man Game",
    videoUrl: "https://www.youtube.com/watch?v=qcN0RdFFF_M",
    duration: "6:20",
    level: "Intermediate",
    tags: ["2-man game", "pick and roll", "screens", "team offense"],
  },
  {
    id: "off-4",
    title: "Motion Offense Principles",
    description: "Teaching the core reads of motion offense: cutting with purpose, spacing, off-ball movement, and when to attack vs. reset. Includes whiteboard and live clips.",
    category: "Offense",
    subcategory: "Motion Offense",
    videoUrl: "https://www.youtube.com/watch?v=J_mHrmWIVDs",
    duration: "8:45",
    level: "Advanced",
    tags: ["motion offense", "spacing", "off-ball", "team concepts"],
  },
  {
    id: "off-5",
    title: "Settled 1-4-1 Set Overview",
    description: "Introduction to the 1-4-1 settled formation. Player positioning, initial looks, and how to create advantages from this set against common defensive alignments.",
    category: "Offense",
    subcategory: "Settled Sets",
    videoUrl: "https://www.youtube.com/watch?v=S8k2L9UXriU",
    duration: "7:10",
    level: "Intermediate",
    tags: ["1-4-1", "settled offense", "formation", "half field"],
  },
  {
    id: "off-6",
    title: "Fast Break Execution",
    description: "Recognizing and executing fast break opportunities. 4v3 and 5v4 break patterns, ball movement speed, lane filling, and finishing under pressure.",
    category: "Offense",
    subcategory: "Fast Break",
    videoUrl: "https://www.youtube.com/watch?v=nrsWBY1NL7E",
    duration: "5:50",
    level: "Beginner",
    tags: ["fast break", "transition", "ball movement", "finishing"],
  },
  {
    id: "off-7",
    title: "EMO: Extra Man Offense Sets",
    description: "Man-up offensive sets including the 3-3 and 1-3-2 formations. Covers ball rotation, identifying the skip lane, and creating high-percentage shots on EMO.",
    category: "Offense",
    subcategory: "EMO",
    videoUrl: "https://www.youtube.com/watch?v=melFnUz0RLM",
    duration: "6:40",
    level: "Advanced",
    tags: ["EMO", "man-up", "special teams", "shooting"],
  },

  // ── Defense ──
  {
    id: "def-1",
    title: "Slide Package: Adjacent Slides",
    description: "Fundamental adjacent slide technique. When to slide, approach angle, stick positioning, and recovery. Includes live game clips showing proper and improper slides.",
    category: "Defense",
    subcategory: "Slide Packages",
    videoUrl: "https://www.youtube.com/watch?v=7uDxcG8BXZ8",
    duration: "6:15",
    level: "Beginner",
    tags: ["slides", "adjacent", "team defense", "help defense"],
  },
  {
    id: "def-2",
    title: "Slide Package: Crease Slides",
    description: "Crease slide responsibilities and timing. Reading the dodge, knowing when to commit, and recovering back to the crease after the slide.",
    category: "Defense",
    subcategory: "Slide Packages",
    videoUrl: "https://www.youtube.com/watch?v=KmAI0yqN_yo",
    duration: "5:30",
    level: "Intermediate",
    tags: ["slides", "crease", "team defense", "communication"],
  },
  {
    id: "def-3",
    title: "On-Ball Defense Fundamentals",
    description: "Proper on-ball defensive stance, footwork, body positioning, and stick checks. Emphasis on forcing direction and maintaining leverage.",
    category: "Defense",
    subcategory: "On-Ball Defense",
    videoUrl: "https://www.youtube.com/watch?v=UGRkkLFv-Vw",
    duration: "4:45",
    level: "Beginner",
    tags: ["on-ball", "footwork", "1v1 defense", "positioning"],
  },
  {
    id: "def-4",
    title: "Double Teams & Traps",
    description: "When and how to execute a double team. Trap locations, communication cues, and capitalizing on the turnover. Covers both planned and reactive doubles.",
    category: "Defense",
    subcategory: "Double Teams",
    videoUrl: "https://www.youtube.com/watch?v=chiLS2PLhLY",
    duration: "5:55",
    level: "Advanced",
    tags: ["double team", "trap", "pressure defense", "communication"],
  },
  {
    id: "def-5",
    title: "Zone Defense: Backer Zone",
    description: "Introduction to the backer zone defense. Responsibilities by position, shifting with the ball, and when to jump passing lanes.",
    category: "Defense",
    subcategory: "Zone Defense",
    videoUrl: "https://www.youtube.com/watch?v=oYd-smuIfIU",
    duration: "7:30",
    level: "Advanced",
    tags: ["zone", "backer", "team defense", "off-ball defense"],
  },
  {
    id: "def-6",
    title: "Defensive Communication",
    description: "The language of team defense. Who calls what, when to call it, and drills to build communication habits. Film clips showing breakdowns caused by silence.",
    category: "Defense",
    subcategory: "On-Ball Defense",
    videoUrl: "https://www.youtube.com/watch?v=XLpXy_AOCfg",
    duration: "4:20",
    level: "Beginner",
    tags: ["communication", "team defense", "leadership"],
  },

  // ── Transition ──
  {
    id: "trans-1",
    title: "Clear Patterns: Settled Clear",
    description: "Primary and secondary clear options from a settled position. Goalie outlets, midfield spacing, and beating a set ride.",
    category: "Transition",
    subcategory: "Clear Patterns",
    videoUrl: "https://www.youtube.com/watch?v=ws0JBImOG0o",
    duration: "5:40",
    level: "Beginner",
    tags: ["clearing", "goalie outlet", "transition", "ball movement"],
  },
  {
    id: "trans-2",
    title: "Ride Schemes: 10-Man Ride",
    description: "Full 10-man ride philosophy and execution. Matchup assignments, forcing turnovers, and converting ride stops into goals.",
    category: "Transition",
    subcategory: "Ride Schemes",
    videoUrl: "https://www.youtube.com/watch?v=Bou0AHGZdfg",
    duration: "6:00",
    level: "Intermediate",
    tags: ["ride", "pressure", "transition defense", "turnovers"],
  },
  {
    id: "trans-3",
    title: "Fast Break Defense",
    description: "How to defend in disadvantage situations. Slowing the break, matching up, and buying time for recovery. 3v4 and 4v5 defensive principles.",
    category: "Transition",
    subcategory: "Fast Break Defense",
    videoUrl: "https://www.youtube.com/watch?v=G81TQs-QhHs",
    duration: "5:10",
    level: "Intermediate",
    tags: ["fast break defense", "recovery", "transition", "man-down"],
  },
  {
    id: "trans-4",
    title: "Outlet Passing & Lane Recognition",
    description: "Reading the ride and finding open outlets. Primary outlet lanes, secondary options, and using eye fakes to open passing lanes.",
    category: "Transition",
    subcategory: "Outlet Passing",
    videoUrl: "https://www.youtube.com/watch?v=j4aQMDaHWRM",
    duration: "4:50",
    level: "Beginner",
    tags: ["outlet", "passing", "clearing", "vision"],
  },

  // ── Rides & Clears ──
  {
    id: "rc-1",
    title: "Riding from the Attack End",
    description: "How attackmen initiate and sustain a ride. Responsibilities after a shot, positioning on turnovers, and communication with midfielders.",
    category: "Rides & Clears",
    subcategory: "Ride Schemes",
    videoUrl: "https://www.youtube.com/watch?v=L2llLgxTsF0",
    duration: "5:20",
    level: "Intermediate",
    tags: ["ride", "attack", "transition", "pressure"],
  },
  {
    id: "rc-2",
    title: "Clear Under Pressure",
    description: "How to clear against an aggressive ride. Reversal options, skip passes, and recognizing when to run vs. pass. Film breakdowns of successful clears under heavy pressure.",
    category: "Rides & Clears",
    subcategory: "Clear Patterns",
    videoUrl: "https://www.youtube.com/watch?v=XBlzyZdhviA",
    duration: "6:30",
    level: "Advanced",
    tags: ["clearing", "pressure", "decision making", "composure"],
  },

  // ── Man-Up/Man-Down ──
  {
    id: "mud-1",
    title: "Man-Up: 3-3 Rotation",
    description: "Core man-up set with 3-3 rotation. Ball movement, skip passes, identifying the unsettled defender, and high-percentage shot opportunities.",
    category: "Man-Up/Man-Down",
    subcategory: "Man-Up Sets",
    videoUrl: "https://www.youtube.com/watch?v=melFnUz0RLM",
    duration: "6:45",
    level: "Intermediate",
    tags: ["man-up", "EMO", "special teams", "rotation"],
  },
  {
    id: "mud-2",
    title: "Man-Down Defense Principles",
    description: "Defensive positioning and rotation in man-down situations. Stick on hands, rotating to the ball, and communicating through the penalty.",
    category: "Man-Up/Man-Down",
    subcategory: "Man-Down Defense",
    videoUrl: "https://www.youtube.com/watch?v=yzzs6kMERok",
    duration: "5:55",
    level: "Advanced",
    tags: ["man-down", "penalty kill", "special teams", "rotation"],
  },

  // ── Goalie ──
  {
    id: "gk-1",
    title: "Goalie Positioning & Arc Play",
    description: "Proper arc positioning relative to the ball. Step-to-the-ball technique, hand positioning, and maintaining the correct depth on the arc at all times.",
    category: "Goalie",
    subcategory: "Positioning",
    videoUrl: "https://www.youtube.com/watch?v=15BSKp0cvgg",
    duration: "5:30",
    level: "Beginner",
    tags: ["goalie", "arc", "positioning", "fundamentals"],
  },
  {
    id: "gk-2",
    title: "Clearing Outlets for Goalies",
    description: "Reading the ride from the cage. Identifying primary, secondary, and emergency outlet options. When to carry vs. when to pass.",
    category: "Goalie",
    subcategory: "Clearing Outlets",
    videoUrl: "https://www.youtube.com/watch?v=q1UVaJsLehw",
    duration: "4:40",
    level: "Intermediate",
    tags: ["goalie", "clearing", "outlet", "decision making"],
  },
  {
    id: "gk-3",
    title: "Goalie Communication System",
    description: "BTB's goalie communication framework. Calling out ball position, slides, and cutters. Building the habit of constant talk from the cage.",
    category: "Goalie",
    subcategory: "Communication",
    videoUrl: "https://www.youtube.com/watch?v=IdibF9roFtM",
    duration: "4:15",
    level: "Beginner",
    tags: ["goalie", "communication", "leadership", "team defense"],
  },
  {
    id: "gk-4",
    title: "High-to-Low Save Technique",
    description: "Mechanics of the high-to-low save. Hand positioning, stepping to the shot, and recovering after a low save. Common mistakes and corrections.",
    category: "Goalie",
    subcategory: "Positioning",
    videoUrl: "https://www.youtube.com/watch?v=IdibF9roFtM",
    duration: "5:00",
    level: "Intermediate",
    tags: ["goalie", "saves", "technique", "shot stopping"],
  },

  // ── Drills ──
  {
    id: "drill-1",
    title: "Ground Ball Circuit",
    description: "Three-station ground ball drill focusing on body positioning, stick angle, and securing the ball under pressure. Includes 1v1 contested ground ball reps.",
    category: "Drills",
    subcategory: "Ground Balls",
    videoUrl: "https://www.youtube.com/watch?v=chiLS2PLhLY",
    duration: "3:45",
    level: "Beginner",
    tags: ["ground balls", "fundamentals", "hustle", "positioning"],
  },
  {
    id: "drill-2",
    title: "Stick Skills Warm-Up Sequence",
    description: "BTB's standard 10-minute stick skills warm-up. Cradling, right/left hand catches, overhand and sidearm throws, quick-stick, and behind-the-back.",
    category: "Drills",
    subcategory: "Stick Skills",
    videoUrl: "https://www.youtube.com/watch?v=7wi4N5_NmrU",
    duration: "4:10",
    level: "Beginner",
    tags: ["stick skills", "warm-up", "catching", "throwing"],
  },
  {
    id: "drill-3",
    title: "Shooting Drill: Catch & Release",
    description: "Rapid catch-and-shoot drill from multiple angles. Emphasis on catching in the shooting position and releasing quickly with accuracy.",
    category: "Drills",
    subcategory: "Shooting Drills",
    videoUrl: "https://www.youtube.com/watch?v=eI7WKifE8aI",
    duration: "5:20",
    level: "Intermediate",
    tags: ["shooting", "accuracy", "quick release", "attack"],
  },
  {
    id: "drill-4",
    title: "Defensive Footwork Ladder",
    description: "Footwork agility drill using a ladder and cones. Drop steps, shuffle slides, and close-out footwork for defenders.",
    category: "Drills",
    subcategory: "Defensive Footwork",
    videoUrl: "https://www.youtube.com/watch?v=ws0JBImOG0o",
    duration: "3:30",
    level: "Beginner",
    tags: ["footwork", "agility", "defense", "conditioning"],
  },
  {
    id: "drill-5",
    title: "2v1 Fast Break Drill",
    description: "Live 2v1 break drill from the midfield line. Ball carrier reads the defender and either finishes or feeds. Rotate offense and defense.",
    category: "Drills",
    subcategory: "Shooting Drills",
    videoUrl: "https://www.youtube.com/watch?v=nrsWBY1NL7E",
    duration: "4:00",
    level: "Intermediate",
    tags: ["fast break", "2v1", "decision making", "finishing"],
  },
  {
    id: "drill-6",
    title: "1v1 Dodging from X",
    description: "Isolated 1v1 reps from behind the cage. Attacker works dodge moves, defender works positioning and recovery. Coach evaluates both sides.",
    category: "Drills",
    subcategory: "Stick Skills",
    videoUrl: "https://www.youtube.com/watch?v=vQfmOqWZa_o",
    duration: "4:45",
    level: "Intermediate",
    tags: ["1v1", "dodging", "attack", "defense"],
  },

  // ── Game Film ──
  {
    id: "gf-1",
    title: "Game Film: Settled Offense Breakdown",
    description: "Full game clip analysis of settled offensive possessions. Identify ball movement patterns, spacing issues, and shot selection tendencies.",
    category: "Game Film",
    subcategory: "Offensive Analysis",
    videoUrl: "https://www.youtube.com/watch?v=4LHsrseSKak",
    duration: "12:30",
    level: "Advanced",
    tags: ["game film", "offense", "analysis", "coaching"],
  },
  {
    id: "gf-2",
    title: "Game Film: Defensive Rotations",
    description: "Game clips focusing on defensive slide timing and rotation. Identifying breakdowns, late slides, and communication failures.",
    category: "Game Film",
    subcategory: "Defensive Analysis",
    videoUrl: "https://www.youtube.com/watch?v=XBlzyZdhviA",
    duration: "10:15",
    level: "Advanced",
    tags: ["game film", "defense", "slides", "analysis"],
  },
  {
    id: "gf-3",
    title: "Game Film: Transition Opportunities",
    description: "Review of transition chances from recent games. Identifying when to push pace and when to pull back. Evaluating clearing and riding effectiveness.",
    category: "Game Film",
    subcategory: "Transition Analysis",
    videoUrl: "https://www.youtube.com/watch?v=dvSS1qWmD1s",
    duration: "8:40",
    level: "Intermediate",
    tags: ["game film", "transition", "clearing", "riding"],
  },
  {
    id: "gf-4",
    title: "Game Film: Faceoff Trends",
    description: "Faceoff clips showing pre-whistle reads, clamp techniques, and wing play. Tendencies and adjustments from recent games.",
    category: "Game Film",
    subcategory: "Faceoff Analysis",
    videoUrl: "https://www.youtube.com/watch?v=EJJ41pSeoGU",
    duration: "6:50",
    level: "Intermediate",
    tags: ["game film", "faceoff", "FOGO", "analysis"],
  },
]

export function getFilmsByCategory(category: FilmCategory): FilmEntry[] {
  return films.filter((f) => f.category === category)
}

export function getFilmById(id: string): FilmEntry | undefined {
  return films.find((f) => f.id === id)
}

export function getRelatedFilms(film: FilmEntry, limit = 4): FilmEntry[] {
  return films
    .filter((f) => f.id !== film.id && f.category === film.category)
    .slice(0, limit)
}

export function searchFilms(query: string): FilmEntry[] {
  const q = query.toLowerCase()
  return films.filter(
    (f) =>
      f.title.toLowerCase().includes(q) ||
      f.description.toLowerCase().includes(q) ||
      f.tags.some((t) => t.toLowerCase().includes(q))
  )
}
